# Generated by Django 2.2.10 on 2020-04-01 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_auto_20200331_0932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditoria',
            old_name='auditoria_id',
            new_name='referencia_id',
        ),
    ]
