# Generated by Django 2.2.11 on 2020-03-26 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sprint8', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='prueba',
        ),
        migrations.CreateModel(
            name='Prueba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(null=True)),
                ('clientes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('productos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sprint8.Producto')),
            ],
        ),
    ]
